### ISSUE TITLE
Rename Post by Tag

### ISSUE THREAD

**Issue by Kalon30** [Kalon30/Portfolio#7]
Want to Change Title "Posts by Tag" to "Topics". 
![Screenshot 2024-03-11 141548](https://github.com/Kalon30/Portfolio/assets/157753954/df707667-5626-4512-bbe2-2b5e02a301ee)

**Comment by dzoladz** [comment]
You'll need to update the `title` metadata in the front matter of `_pages/tag-archive.md` to rename that value
